version: "3.7"

services:
#  postgres:
#    image: postgres:12
#    container_name: postgres
#    restart: unless-stopped
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./sql:/docker-entrypoint-initdb.d
#    environment:
#      POSTGRES_PASSWORD: p@ssw0rd
#      POSTGRES_USER: shortener
#      POSTGRES_DB: shortener
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U shortener -d shortener"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 10s
#    networks:
#      - url-shortener-net

  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      PG_DSN: "postgres://postgres:1110@postgres/test?sslmode=disable"
#    depends_on:
#      - postgres
    networks:
      - url-shortener-net

networks:
  url-shortener-net:
