name: golangci-lint
on:
  push:
    branches-ignore:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43.0
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic --tags=integration ./...
  #      - name: Upload coverage to Codecov
  #        run: bash <(curl -s https://codecov.io/bash)
